// Mocks generated by Mockito 5.3.2 from annotations
// in spotify_lite/test/bloc/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spotify_lite/models/authentication.dart' as _i3;
import 'package:spotify_lite/models/spotify/search_result.dart' as _i4;
import 'package:spotify_lite/services/spotify_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthenticationModel_1 extends _i1.SmartFake
    implements _i3.AuthenticationModel {
  _FakeAuthenticationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchResult_2 extends _i1.SmartFake implements _i4.SearchResult {
  _FakeSearchResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SpotifyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpotifyService extends _i1.Mock implements _i5.SpotifyService {
  MockSpotifyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get clientId => (super.noSuchMethod(
        Invocation.getter(#clientId),
        returnValue: '',
      ) as String);
  @override
  String get clientSecret => (super.noSuchMethod(
        Invocation.getter(#clientSecret),
        returnValue: '',
      ) as String);
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  _i6.Future<_i3.AuthenticationModel> getUserAuthenticatedSpotifyApi(
          String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAuthenticatedSpotifyApi,
          [code],
        ),
        returnValue: _i6.Future<_i3.AuthenticationModel>.value(
            _FakeAuthenticationModel_1(
          this,
          Invocation.method(
            #getUserAuthenticatedSpotifyApi,
            [code],
          ),
        )),
      ) as _i6.Future<_i3.AuthenticationModel>);
  @override
  _i6.Future<_i4.SearchResult> searchItems(
    _i3.AuthenticationModel? authenticationModel,
    String? searchTerms, [
    int? offset = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchItems,
          [
            authenticationModel,
            searchTerms,
            offset,
          ],
        ),
        returnValue: _i6.Future<_i4.SearchResult>.value(_FakeSearchResult_2(
          this,
          Invocation.method(
            #searchItems,
            [
              authenticationModel,
              searchTerms,
              offset,
            ],
          ),
        )),
      ) as _i6.Future<_i4.SearchResult>);
}
